# Generated by Django 2.2.7 on 2019-11-26 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(help_text='Nombre del servicio', max_length=45, unique=True, verbose_name='Nombre servicio')),
                ('hora_inicio_servicio', models.TimeField(help_text='Hora de inicio', verbose_name='Hora inicio')),
                ('hora_fin_servicio', models.TimeField(help_text='Hora de fin', verbose_name='Hora fin')),
                ('valor_servicio', models.PositiveIntegerField(help_text='Valor del servicio', verbose_name='Valor servicio')),
                ('servicio_lunes', models.BooleanField(default=True, help_text='El servicio se presta el lunes', verbose_name='Lunes')),
                ('servicio_martes', models.BooleanField(default=True, help_text='El servicio se presta el martes', verbose_name='martes')),
                ('servicio_miercoles', models.BooleanField(default=True, help_text='El servicio se presta el miércoles', verbose_name='Miercoles')),
                ('servicio_jueves', models.BooleanField(default=True, help_text='El servicio se presta el jueves', verbose_name='Jueves')),
                ('servicio_viernes', models.BooleanField(default=True, help_text='El servicio se presta el viernes', verbose_name='Viernes')),
                ('servicio_sabado', models.BooleanField(default=True, help_text='El servicio se presta el sábado', verbose_name='Sábado')),
                ('uc', models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Habilitacion_servicio',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('id_habilitacion_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_habilitacion_servicio', models.DateField(help_text='Fecha en que se habilita prestar un servicio', verbose_name='Fecha habilitación servicio')),
                ('habilitado_habilitacion_servicio', models.BooleanField(help_text='Activo si se presta el servicio', verbose_name='Estado')),
                ('servicio_habilitacion_servicio', models.ForeignKey(help_text='Servicio a habilitar', on_delete=False, to='servicios.Servicio', verbose_name='Servicio a habilitar')),
                ('uc', models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
