# Generated by Django 2.2.7 on 2019-11-26 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beneficiarios', '0006_auto_20191126_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('id_recarga', models.AutoField(primary_key=True, serialize=False)),
                ('valor_recarga', models.PositiveIntegerField(help_text='Valor recargado', verbose_name='Valor recarga')),
                ('beneficiario_recarga_saldo', models.ForeignKey(help_text='Nombre del beneficiario', on_delete=False, to='beneficiarios.Beneficiario', verbose_name='Nombre beneficiario')),
                ('uc', models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recarga',
                'verbose_name_plural': 'Recargas',
            },
        ),
    ]
