# Generated by Django 2.2.7 on 2019-11-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_dependencia_documento_identidad_tipo_beneficiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='nombre_dependencia',
            field=models.CharField(help_text='Nombre de la dependencia a la que pertenece, ej: Sistemas, Vigilancia', max_length=45, unique=True, verbose_name='Nombre dependencia'),
        ),
        migrations.AlterField(
            model_name='documento_identidad',
            name='nombre_documento_identidad',
            field=models.CharField(help_text='Nombre del documento de identidad', max_length=45, unique=True, verbose_name='Nombre documento'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre_genero',
            field=models.CharField(help_text='Nombre del género', max_length=45, unique=True, verbose_name='Nombre género'),
        ),
        migrations.AlterField(
            model_name='tipo_beneficiario',
            name='nombre_tipo_beneficiario',
            field=models.CharField(help_text='Nombre del tipo de beneficiario, ej: Estudiante Bachillerato', max_length=45, unique=True, verbose_name='nombre tipo beneficiario'),
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('id_rfid_beneficiario', models.CharField(help_text='Id RFID carné o llavero', max_length=45, unique=True, verbose_name='Id RFID')),
                ('numero_documento_identidad_beneficiario', models.CharField(help_text='Número del documento de identidad del beneficiario', max_length=15, unique=True, verbose_name='Número de documento de identidad')),
                ('nombres_beneficiario', models.CharField(help_text='Nombres del beneficiario', max_length=45, verbose_name='Nombres')),
                ('apellidos_beneficiario', models.CharField(help_text='Apellidos del beneficiario', max_length=45, verbose_name='Apellidos')),
                ('email_beneficiario', models.EmailField(help_text='Correo electrónico del beneficiario', max_length=70, unique=True, verbose_name='Correo electrónico')),
                ('fecha_nacimiento_beneficiario', models.DateField(help_text='Fecha de nacimiento del beneficiario en el formato <em>AAAA-MM-DD</em>', verbose_name='Fecha de nacimiento')),
                ('saldo_beneficiario', models.IntegerField(editable=False, verbose_name='Saldo')),
                ('foto_beneficiario', models.ImageField(upload_to='beneficiarios')),
                ('dependencia_beneficiario', models.ForeignKey(help_text='Dependencia a la que pertenece', on_delete=False, to='beneficiarios.Dependencia', verbose_name='Dependencia')),
                ('documento_identidad', models.ForeignKey(help_text='Documento de identidad del beneficiario', on_delete=False, to='beneficiarios.Documento_identidad', verbose_name='Documento de identidad')),
                ('genero_beneficiario', models.ForeignKey(help_text='Gérero del beneficiario', on_delete=False, to='beneficiarios.Genero', verbose_name='Género')),
                ('tipo_beneficiario', models.ForeignKey(help_text='Tipo de beneficiario', on_delete=False, to='beneficiarios.Tipo_beneficiario', verbose_name='Tipo beneficiario')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
    ]
