# Generated by Django 2.2.7 on 2019-11-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_auto_20191123_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_documento_identidad_beneficiario',
            field=models.CharField(help_text='Número del documento de identidad del beneficiario', max_length=15, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='saldo_beneficiario',
            field=models.IntegerField(default=0, editable=False, verbose_name='Saldo'),
        ),
    ]
