# Generated by Django 2.2.7 on 2019-11-26 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0005_auto_20191124_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='apellidos_beneficiario',
            field=models.CharField(max_length=45, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='email_beneficiario',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='fecha_nacimiento_beneficiario',
            field=models.DateField(help_text='<em>AAAA-MM-DD</em>', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='id_rfid_beneficiario',
            field=models.CharField(help_text='Id RFID carné o llavero    ', max_length=45, unique=True, verbose_name='Id RFID'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nombres_beneficiario',
            field=models.CharField(max_length=45, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='uc',
            field=models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='um',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='uc',
            field=models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='um',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='documento_identidad',
            name='uc',
            field=models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento_identidad',
            name='um',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='uc',
            field=models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genero',
            name='um',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_beneficiario',
            name='uc',
            field=models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipo_beneficiario',
            name='um',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
